# Path to your oh-my-zsh installation.
export ZSH=/home/arthur/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git symfony2 composer docker docker-compose yarn postgres zsh-autosuggestions zsh-syntax-highlighting history-sync)

# User configuration

export GOPATH="/home/arthur/go"
export GO111MODULE=on

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/snap/bin"
export PATH="${PATH}:/home/arthur/.local/bin:/home/arthur/bin:/home/arthur/scripts"
export PATH="${PATH}:/home/arthur/.config/yarn/global/node_modules/.bin"
export PATH="${PATH}:${GOPATH}/bin"
export PATH="${PATH}:/home/arthur/.gem/ruby/2.7.0/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh
source ~/installs/key-bindings.zsh
#source /usr/share/fzf/completion.zsh

# Add a line break to Oh my ZSH prompt
prompt_end() {
  if [[ -n $CURRENT_BG ]]; then
      print -n "%{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
  else
      print -n "%{%k%}"
  fi

  print -n "%{%f%}"
  CURRENT_BG=''

  #Adds the new line and ➜ as the start character.
  printf "\n ➜";
}

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
export VISUAL=vim
export EDITOR="$VISUAL"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Moved that to local file
# export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/jre
# export LD_LIBRARY_PATH=/usr/lib64/nvidia:${LD_LIBRARY_PATH}

export DEFAULT_USER=arthur

#export WORKON_HOME=~/pyenvs
#source /usr/bin/virtualenvwrapper.sh
alias gst='git status'
alias git='git '
alias poule=pull

# added by travis gem
[ -f /home/arthur/.travis/travis.sh ] && source /home/arthur/.travis/travis.sh

f_dockerin() {
    docker exec -i -t $1 bash
}
alias dockerin=f_dockerin

f_dockerinsh() {
    docker exec -i -t $1 sh
}
alias dockerinsh=f_dockerinsh
alias de="docker-compose exec -T"

#alias yarn=nodejs-yarn
alias de="docker-compose exec"
alias cat=bat
alias catp=bat -p
alias ping="prettyping --nolegend"
alias preview="fzf --preview 'bat --color \"always\" {}'"
alias du="ncdu --color dark -x --exclude .git --exclude node_modules"
alias yrb="yarn run build"
alias yrd="yarn run dev"
alias yrs="yarn run serve"
alias vimi="vim +PluginInstall +qall"
alias runlike="docker run --rm -v /var/run/docker.sock:/var/run/docker.sock assaflavie/runlike"

if [ -f /etc/lsb-release ]; then
  alias up="sudo apt-get update && sudo apt-get upgrade"
  alias i="sudo apt-get install"
elif [ -f /etc/redhat-release ]; then
  alias up="sudo dnf update"
  alias i="sudo dnf install"
fi

if hash ifconfig 2>/dev/null; then
else
  alias ifconfig="ip -c a"
fi

eval $(thefuck --alias)

source ~/.dotfiles/zsh/zshrc.local

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

thefuck -v >/dev/null 2>&1 && eval $(thefuck --alias)

return 0

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/bit bit
